# Deployment do MongoFB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP

---

# Deployment da aplicação web Rotten Potatoes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: fabricioveronez/rotten-potatoes:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
<<<<<<< HEAD
=======

>>>>>>> a707645408f4bf2a9d21eb4664c609a56504221d


###
# MONGODB_DB => Nome do database
#
# MONGODB_HOST => Host do MongoDB
#
# MONGODB_PORT => Posta de acesso ao MongoDB
#
# MONGODB_USERNAME => Usuário do MongoDB
#
# MONGODB_PASSWORD => Senha do MongoDB
#
# O "nodePort: 3000" é a porta local do K3D, "port: 80" é do service web HTTP e "targetPort: 5000" é a porta do pod a porta de destino
###
